/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "outputWriter/XYZWriter.h"
#include <iomanip>
#include <sstream>
#include <unordered_map>
#include <iostream>

namespace outputWriter {

XYZWriter::XYZWriter() = default;

XYZWriter::~XYZWriter() = default;

void XYZWriter::plotParticles(std::unordered_map<int, Particle>& particles,
                              const std::string &filename, int iteration) {
  std::ofstream file;
  std::stringstream strstr;
  strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

  file.open(strstr.str().c_str());
  file << particles.size() << std::endl;
  file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
          "file format doku."
       << std::endl;

  for (auto &p : particles) {
//    std::array<double, 3> x = p.second.getX();
    file << "Ar ";
    file.setf(std::ios_base::showpoint);

    for (auto &xi : p.second.getX()) {
      file << xi << " ";
    }

    file << std::endl;
  }

  file.close();
}

} // namespace outputWriter
