/*
 * ParticleContainer.h
 *
 *  Created on: 30.10.2022
 *      Author: Team-B
 */

#include "Particle.h"
#include <unordered_map>
#include "ParticleContainer.h"
#include <iostream>
#include"spdlog/spdlog.h"



	int ParticleContainer::getParticle_counter() const {
		return particle_counter;
	}
	 std::unordered_map<int, Particle> &ParticleContainer::getParticles()  {
		return Particles;
	}

	ParticleContainer::~ParticleContainer() { spdlog::info("Particle destructed!"); }

	ParticleContainer::ParticleContainer(const ParticleContainer &other) {
		particle_counter = other.particle_counter;
		Particles = other.Particles;
		spdlog::info("ParticleContainer generated by copy!");
		
	}

	ParticleContainer::ParticleContainer(std::unordered_map<int, Particle>& Particles_arg, int& particle_counter_arg)
		:Particles(Particles_arg), particle_counter(particle_counter_arg)
	{
		spdlog::info("ParticleContainer generated !");
	}
    void ParticleContainer::setParticleCounter(int x) {
        particle_counter = x;
}
