name: Lint Code

on:
  push:
    branches:
      - "AlexTestBranch"
      - "main"
  pull_request:
    branches:
      - "AlexTestBranch"
      - "main"
      
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false # this is necessary, since it doesn´t like the library style
          VALIDATE_C++_CPP-LINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
     
